version: '3.9'

services:
  itask_mysql:
    image: mysql
    container_name: docker-compose.yaml
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=esim
    volumes:
      - database_mysql:/var/lib/mysql
      - ./db/itask.sql:/docker-entrypoint-initdb.d/itask.sql
    networks:
      - itask_network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - itask_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: itask-app-api
    ports:
      - "8080:8080"
    networks:
      - itask_network
    depends_on:
      - itask_mysql
      - redis
    command: ["sh", "/app/wait-for-it.sh", "project_personal:3309", "--", "/app/itask"]

volumes:
  database_mysql:

networks:
  itask_network:
    driver: bridge
